##
## This is an automagically generated file. Do NOT EDIT.
## Any changes you make will be overwritten!!
##
## Make changes to the SIMH top-level makefile and then run the
## "cmake/generate.py" script to regenerate these files.
##
##     cd cmake; python -m generate --help
##
## ------------------------------------------------------------
set(ALPHAD     "${CMAKE_SOURCE_DIR}/alpha")
set(ALTAIRD    "${CMAKE_SOURCE_DIR}/ALTAIR")
set(ALTAIRZ80D "${CMAKE_SOURCE_DIR}/AltairZ80")
set(ATT3B2D    "${CMAKE_SOURCE_DIR}/3B2")
set(B5500D     "${CMAKE_SOURCE_DIR}/B5500")
set(BESM6D     "${CMAKE_SOURCE_DIR}/BESM6")
set(CDC1700D   "${CMAKE_SOURCE_DIR}/CDC1700")
set(GRID       "${CMAKE_SOURCE_DIR}/GRI")
set(H316D      "${CMAKE_SOURCE_DIR}/H316")
set(HP2100D    "${CMAKE_SOURCE_DIR}/HP2100")
set(HP3000D    "${CMAKE_SOURCE_DIR}/HP3000")
set(I1401D     "${CMAKE_SOURCE_DIR}/I1401")
set(I1620D     "${CMAKE_SOURCE_DIR}/I1620")
set(I650D      "${CMAKE_SOURCE_DIR}/I650")
set(I7000D     "${CMAKE_SOURCE_DIR}/I7000")
set(I7010D     "${CMAKE_SOURCE_DIR}/I7000")
set(I7094D     "${CMAKE_SOURCE_DIR}/I7094")
set(IBM1130D   "${CMAKE_SOURCE_DIR}/Ibm1130")
set(ID16D      "${CMAKE_SOURCE_DIR}/Interdata")
set(ID32D      "${CMAKE_SOURCE_DIR}/Interdata")
set(IMLACD     "${CMAKE_SOURCE_DIR}/imlac")
set(INTELSYSC  "${CMAKE_SOURCE_DIR}/Intel-Systems/common")
set(KA10D      "${CMAKE_SOURCE_DIR}/PDP10")
set(KI10D      "${CMAKE_SOURCE_DIR}/PDP10")
set(KL10D      "${CMAKE_SOURCE_DIR}/PDP10")
set(KS10D      "${CMAKE_SOURCE_DIR}/PDP10")
set(LGPD       "${CMAKE_SOURCE_DIR}/LGP")
set(ND100D     "${CMAKE_SOURCE_DIR}/ND100")
set(NOVAD      "${CMAKE_SOURCE_DIR}/NOVA")
set(PDP10D     "${CMAKE_SOURCE_DIR}/PDP10")
set(PDP11D     "${CMAKE_SOURCE_DIR}/PDP11")
set(PDP18BD    "${CMAKE_SOURCE_DIR}/PDP18B")
set(PDP1D      "${CMAKE_SOURCE_DIR}/PDP1")
set(PDP6D      "${CMAKE_SOURCE_DIR}/PDP10")
set(PDP8D      "${CMAKE_SOURCE_DIR}/PDP8")
set(PDQ3D      "${CMAKE_SOURCE_DIR}/PDQ-3")
set(S3D        "${CMAKE_SOURCE_DIR}/S3")
set(SAGED      "${CMAKE_SOURCE_DIR}/SAGE")
set(SDSD       "${CMAKE_SOURCE_DIR}/SDS")
set(SEL32D     "${CMAKE_SOURCE_DIR}/SEL32")
set(SIGMAD     "${CMAKE_SOURCE_DIR}/sigma")
set(SSEMD      "${CMAKE_SOURCE_DIR}/SSEM")
set(SWTP6800C  "${CMAKE_SOURCE_DIR}/swtp6800/common")
set(SWTP6800D  "${CMAKE_SOURCE_DIR}/swtp6800/swtp6800")
set(TT2500D    "${CMAKE_SOURCE_DIR}/tt2500")
set(TX0D       "${CMAKE_SOURCE_DIR}/TX-0")
set(UC15D      "${CMAKE_SOURCE_DIR}/PDP11")
set(VAXD       "${CMAKE_SOURCE_DIR}/VAX")

set(DISPLAYD   "${CMAKE_SOURCE_DIR}/display")
set(DISPLAY340 "${DISPLAYD}/type340.c")
set(DISPLAYIII "${DISPLAYD}/iii.c")
set(DISPLAYNG  "${DISPLAYD}/ng.c")
set(DISPLAYVT  "${DISPLAYD}/vt11.c")

set(INTELSYSD  "${CMAKE_SOURCE_DIR}/Intel-Systems")
set(INTEL_MDSD "${INTELSYSD}/Intel-MDS")
set(SCELBIC    "${INTELSYSD}/common")
set(SCELBID    "${INTELSYSD}/scelbi")

## ----------------------------------------

if (NOT WITH_VIDEO)
    ### Hack: Unset these variables so that they don't expand if
    ### not building with video:
    set(DISPLAY340 "")
    set(DISPLAYIII "")
    set(DISPLAYNG  "")
    set(DISPLAYVT  "")
endif ()

## ----------------------------------------

add_subdirectory(3B2)
add_subdirectory(ALTAIR)
add_subdirectory(AltairZ80)
add_subdirectory(B5500)
add_subdirectory(BESM6)
add_subdirectory(CDC1700)
add_subdirectory(GRI)
add_subdirectory(H316)
add_subdirectory(HP2100)
add_subdirectory(HP3000)
add_subdirectory(I1401)
add_subdirectory(I1620)
add_subdirectory(I650)
add_subdirectory(I7000)
add_subdirectory(I7094)
add_subdirectory(Ibm1130)
add_subdirectory(Intel-Systems/Intel-MDS)
add_subdirectory(Intel-Systems/scelbi)
add_subdirectory(Interdata)
add_subdirectory(LGP)
add_subdirectory(ND100)
add_subdirectory(NOVA)
add_subdirectory(PDP1)
add_subdirectory(PDP10)
add_subdirectory(PDP11)
add_subdirectory(PDP18B)
add_subdirectory(PDP8)
add_subdirectory(PDQ-3)
add_subdirectory(S3)
add_subdirectory(SAGE)
add_subdirectory(SDS)
add_subdirectory(SEL32)
add_subdirectory(SSEM)
add_subdirectory(TX-0)
add_subdirectory(VAX)
add_subdirectory(alpha)
add_subdirectory(imlac)
add_subdirectory(sigma)
add_subdirectory(swtp6800/swtp6800)
add_subdirectory(tt2500)
